[GLOBAL]
pants_version = "2.30.0"
backend_packages = [
  "pants.backend.python",
  "pants.backend.plugin_development",
  "ocaml",
]
pythonpath = ["%(buildroot)s"]

[python]
interpreter_constraints = ["==3.14.*"]
